version: "3"
services:

  mysql:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Jakarta
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 30s
      retries: 10
    # volumes:
    #   - ./dummy_data:/docker-entrypoint-initdb.d/

  mysql2:
    image: mysql:8.0.36
    ports:
      - 3308:3306
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Jakarta
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 30s
      retries: 10
    # volumes:
    #   - ./dummy_data2:/docker-entrypoint-initdb.d/

  proxysql:
    image: proxysql/proxysql:2.5.5
    restart: unless-stopped
    volumes:
      - "./proxysql.cnf:/etc/proxysql.cnf"
      - "./proxysql:/var/lib/proxysql"
    ports:
      - "6033:6033"
      - "6032:6032"
      - "6080:6080"
    links:
      - mysql
      - mysql2
    depends_on:
      mysql:
        condition: service_healthy
      mysql2:
        condition: service_healthy

  pma:
    image: phpmyadmin
    container_name: adminer
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PMA_ARBITRARY=1
